[project]
name = "blogermenia-djnago"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=46.0.3",
    "pillow>=12.0.0",
    "pyjwt>=2.10.1",
    "requests>=2.32.5",
]
